org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx4g"
kotlin.code.style=official
#
forAGP410=false
android.useAndroidX=true

UPLOAD_SOURCE=true

bytekmp.disable.kotlin.version.check=true

ARTIFACT_VERSION = 9.9.9.9-local
custom_maven_url=https://artifact.bytedance.com/repository/releases/
#org.gradle.jvmargs=-Xdebug -Xrunjdwp:transport=dt_socket,address=5005,server=y,suspend=n